# Workflow API version
apiVersion: io.orquestra.workflow/1.0.0

# Prefix for workflow ID
name: dingo8

imports:
- name: isingdata
  type: git
  parameters:
    repository: "git@github.com:kottmanj/isingdata.git"
    branch: "master"

steps:





- name: ising-0
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 5
      type: int
    - n_trials: 3
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
  outputs:
    - name: isingdata
      type: isingdata

- name: ising-1
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 5
      type: int
    - n_trials: 3
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
  outputs:
    - name: isingdata
      type: isingdata

- name: ising-2
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 5
      type: int
    - n_trials: 3
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
  outputs:
    - name: isingdata
      type: isingdata

- name: ising-3
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 5
      type: int
    - n_trials: 3
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
  outputs:
    - name: isingdata
      type: isingdata

- name: ising-4
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 5
      type: int
    - n_trials: 3
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
  outputs:
    - name: isingdata
      type: isingdata

- name: ising-5
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 5
      type: int
    - n_trials: 3
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
  outputs:
    - name: isingdata
      type: isingdata

- name: ising-6
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 5
      type: int
    - n_trials: 3
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
  outputs:
    - name: isingdata
      type: isingdata

- name: ising-7
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 5
      type: int
    - n_trials: 3
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
  outputs:
    - name: isingdata
      type: isingdata

- name: ising-8
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 5
      type: int
    - n_trials: 3
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
  outputs:
    - name: isingdata
      type: isingdata

- name: ising-9
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 5
      type: int
    - n_trials: 3
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
  outputs:
    - name: isingdata
      type: isingdata


types:
  - isingdata

