# Workflow API version
apiVersion: io.orquestra.workflow/1.0.0

# Prefix for workflow ID
name: dingo6-optim

imports:
- name: isingdata
  type: git
  parameters:
    repository: "git@github.com:kottmanj/isingdata.git"
    branch: "master"

steps:






- name: ising-0
  config:
    runtime:
      language: python3
      imports: [isingdata]
      parameters:
        file: isingdata/steps/run.py
        function: run_ising_circuits
  inputs:
    - n_qubits: 6
      type: int
    - n_circuits: 1
      type: int
    - n_trials: 1
      type: int
    - generators: '["XY", "Y"]'
      type: string
    - fix_angles: '{"XY": 1.5707963267948966}'
      type: string
    - fix_mean_field: True
      type: bool
    - n_samples: 1
      type: int
  outputs:
    - name: isingdata
      type: isingdata


types:
  - isingdata

